/**
 * Página do assistente de configuração (v2.6) — HTML/CSS/JS embutido.
 * Segue o visual do overlay (dark gamer, verde/roxo) e NÃO usa recursos
 * externos: funciona offline e dentro do .exe empacotado.
 *
 * Segurança: nenhum dado do usuário ou do servidor vira HTML — tudo é
 * inserido via textContent / .value (sem innerHTML de dados). Os segredos
 * salvos voltam para os campos MASCARADOS (v2.8.1): o valor em claro nunca
 * é entregue ao navegador; deixar a máscara como está = manter o valor
 * salvo no .env (o servidor reconhece e resolve).
 */

const PAGINA = [
  '<!DOCTYPE html>',
  '<html lang="pt-BR">',
  '<head>',
  '<meta charset="UTF-8">',
  '<meta name="viewport" content="width=device-width, initial-scale=1">',
  '<title>ChatPlays — Assistente</title>',
  '<style>',
  '* { margin: 0; padding: 0; box-sizing: border-box; }',
  'body {',
  '  font-family: "Segoe UI", "Noto Sans", system-ui, sans-serif;',
  '  background: linear-gradient(135deg, #0b0d13 0%, #12161f 100%);',
  '  background-attachment: fixed;',
  '  color: #e8ecf3; padding: 28px 16px 120px;',
  '}',
  '.wrap { max-width: 900px; margin: 0 auto; }',
  'header { text-align: center; margin-bottom: 26px; }',
  'header h1 { font-size: 26px; letter-spacing: 0.5px; }',
  'header h1 .pkm { color: #facc15; }',
  'header .sub { color: #8b98ab; margin-top: 6px; font-size: 14px; }',
  'header .versao {',
  '  display: inline-block; margin-top: 10px; padding: 3px 12px;',
  '  background: rgba(250,204,21,0.15); color: #facc15; border-radius: 999px;',
  '  font-size: 12px; font-weight: 600;',
  '}',
  '.card {',
  '  background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08);',
  '  border-radius: 14px; padding: 22px; margin-bottom: 18px;',
  '}',
  '.card.inativo { opacity: 0.45; }',
  '.card-top { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 14px; }',
  '.card-top h2 { font-size: 18px; display: flex; align-items: center; gap: 8px; }',
  '.card-top .badge-plat { font-size: 11px; color: #8b98ab; font-weight: 400; }',
  '.campo { margin-bottom: 14px; }',
  '.campo label { display: block; font-size: 13px; color: #aab5c6; margin-bottom: 5px; font-weight: 600; }',
  '.campo input, .campo select {',
  '  width: 100%; padding: 10px 12px; font-size: 14px;',
  '  background: #0e131c; border: 1px solid rgba(255,255,255,0.12);',
  '  border-radius: 9px; color: #e8ecf3; outline: none;',
  '  transition: border-color 0.15s, box-shadow 0.15s;',
  '}',
  '.campo input:focus, .campo select:focus { border-color: #22c55e; box-shadow: 0 0 0 3px rgba(34,197,94,0.18); }',
  '.campo input[type=password] { font-family: Consolas, monospace; letter-spacing: 0.5px; }',
  '.campo .dica { font-size: 12px; color: #77839a; margin-top: 5px; line-height: 1.5; }',
  '.campo .dica a { color: #7dd3fc; }',
  '.linha { display: flex; gap: 14px; } .linha .campo { flex: 1; }',
  '.hint-id { font-size: 12px; margin-top: 5px; color: #86efac; display: none; }',
  '.hint-salvo { font-size: 12px; margin-top: 5px; color: #86efac; display: none; }',
  '.caminho input { font-family: Consolas, monospace; font-size: 13px; }',
  '.linha-toggle { display: flex; align-items: center; justify-content: space-between; gap: 14px; padding: 12px 14px; margin-top: 4px; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.07); border-radius: 10px; }',
  '.linha-toggle .titulo { font-size: 14px; font-weight: 600; }',
  '.linha-toggle .sub { font-size: 12px; color: #77839a; margin-top: 3px; line-height: 1.5; }',
  '.switch { position: relative; width: 52px; height: 28px; flex: none; }',
  '.switch input { opacity: 0; width: 100%; height: 100%; position: absolute; cursor: pointer; z-index: 2; margin: 0; }',
  '.switch .trilho {',
  '  position: absolute; inset: 0; background: #2a3345; border-radius: 999px;',
  '  transition: background 0.18s;',
  '}',
  '.switch .bola {',
  '  position: absolute; top: 3px; left: 3px; width: 22px; height: 22px;',
  '  background: #8b98ab; border-radius: 50%; transition: left 0.18s, background 0.18s;',
  '}',
  '.switch input:checked ~ .trilho { background: rgba(34,197,94,0.35); }',
  '.switch input:checked ~ .bola { left: 27px; background: #22c55e; box-shadow: 0 0 10px rgba(34,197,94,0.6); }',
  '.acoes-plat { display: flex; align-items: center; gap: 12px; margin-top: 6px; }',
  '.btn {',
  '  padding: 10px 18px; font-size: 14px; font-weight: 600; cursor: pointer;',
  '  border-radius: 9px; border: 1px solid rgba(255,255,255,0.12);',
  '  background: #1e293b; color: #e8ecf3; transition: background 0.15s, transform 0.08s;',
  '}',
  '.btn:hover { background: #273549; } .btn:active { transform: scale(0.97); }',
  '.btn:disabled { opacity: 0.5; cursor: wait; }',
  '.btn.teste { background: rgba(167,139,250,0.15); border-color: rgba(167,139,250,0.35); color: #c4b5fd; }',
  '.btn.teste:hover { background: rgba(167,139,250,0.25); }',
  '.res { flex: 1; font-size: 13px; line-height: 1.5; display: none; padding: 8px 12px; border-radius: 8px; }',
  '.res.ok { display: block; background: rgba(34,197,94,0.12); color: #86efac; }',
  '.res.err { display: block; background: rgba(239,68,68,0.12); color: #fca5a5; }',
  '.res.aguardando { display: block; background: rgba(250,204,21,0.12); color: #fde68a; }',
  '.spinner {',
  '  display: inline-block; width: 14px; height: 14px; vertical-align: -2px;',
  '  border: 2px solid rgba(255,255,255,0.25); border-top-color: #fff;',
  '  border-radius: 50%; animation: girar 0.7s linear infinite; margin-right: 8px;',
  '}',
  '@keyframes girar { to { transform: rotate(360deg); } }',
  '.cmd-exemplos { display: flex; flex-wrap: wrap; gap: 7px; margin-top: 10px; }',
  '.cmd-chip { padding: 6px 10px; border-radius: 999px; border: 1px solid rgba(125,211,252,0.25); background: rgba(125,211,252,0.08); color: #bae6fd; cursor: pointer; font-size: 12px; }',
  '.cmd-chip:hover { background: rgba(125,211,252,0.16); }',
  '#res-teste-comando { white-space: pre-line; }',
  'details.avancado { border: 1px solid rgba(255,255,255,0.08); border-radius: 14px; background: rgba(255,255,255,0.02); }',
  'details.avancado summary {',
  '  padding: 16px 22px; cursor: pointer; font-size: 15px; font-weight: 600;',
  '  color: #aab5c6; list-style: none; user-select: none;',
  '}',
  'details.avancado summary::-webkit-details-marker { display: none; }',
  'details.avancado summary:before { content: "⚙  "; }',
  'details.avancado[open] summary { border-bottom: 1px solid rgba(255,255,255,0.08); }',
  'details.avancado .card { border: none; background: transparent; margin: 0; }',
  '.erros-gerais {',
  '  display: none; background: rgba(239,68,68,0.12); border: 1px solid rgba(239,68,68,0.35);',
  '  color: #fca5a5; border-radius: 10px; padding: 14px 18px; margin-bottom: 16px;',
  '  font-size: 13px; line-height: 1.6;',
  '}',
  '.barra-fix {',
  '  position: fixed; left: 0; right: 0; bottom: 0; z-index: 10;',
  '  background: rgba(11,13,19,0.92); backdrop-filter: blur(8px);',
  '  border-top: 1px solid rgba(255,255,255,0.08); padding: 14px 16px;',
  '}',
  '.barra-fix .dentro { max-width: 900px; margin: 0 auto; display: flex; align-items: center; gap: 14px; }',
  '.btn.primario {',
  '  background: linear-gradient(135deg, #16a34a, #22c55e); border-color: rgba(34,197,94,0.6);',
  '  color: #052e16; font-size: 15px; padding: 12px 26px;',
  '  box-shadow: 0 4px 18px rgba(34,197,94,0.35);',
  '}',
  '.btn.primario:hover { background: linear-gradient(135deg, #15803d, #16a34a); }',
  '.btn.fantasma { background: transparent; color: #8b98ab; }',
  '.btn.fantasma:hover { color: #e8ecf3; background: rgba(255,255,255,0.05); }',
  '.status { font-size: 12px; color: #8b98ab; margin-left: auto; }',
  '.status .pt { display: inline-block; width: 9px; height: 9px; border-radius: 50%; margin-right: 6px; background: #3a475a; }',
  '.status.on .pt { background: #22c55e; box-shadow: 0 0 8px #22c55e; }',
  '#tela-sucesso { display: none; text-align: center; padding: 60px 20px; }',
  '#tela-sucesso .emoji { font-size: 64px; margin-bottom: 16px; }',
  '#tela-sucesso h2 { font-size: 26px; margin-bottom: 10px; color: #86efac; }',
  '#tela-sucesso p { color: #aab5c6; font-size: 15px; line-height: 1.7; max-width: 520px; margin: 0 auto 8px; }',
  '#tela-sucesso .passos { text-align: left; background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; padding: 18px 24px; max-width: 560px; margin: 22px auto; font-size: 14px; line-height: 2; color: #c8d2e0; }',
  '.olho { position: absolute; right: 9px; top: 34px; background: none; border: none; cursor: pointer; font-size: 16px; opacity: 0.7; }',
  '.rel { position: relative; }',
  '/* ---------- v2.9: Controles do Chat ---------- */',
  '.ctl-cab, .ctl-row {',
  '  display: grid; grid-template-columns: 46px 1.05fr 160px 1.5fr auto;',
  '  gap: 8px; align-items: center;',
  '}',
  '.ctl-cab { font-size: 11px; color: #77839a; font-weight: 700; padding: 0 2px 8px; letter-spacing: 0.3px; }',
  '.ctl-row { padding: 9px 2px; border-bottom: 1px solid rgba(255,255,255,0.06); }',
  '.ctl-row:last-child { border-bottom: none; }',
  '.ctl-row.off { opacity: 0.45; }',
  '.ctl-row input[type=text] {',
  '  width: 100%; padding: 9px 10px; font-size: 13px;',
  '  background: #0e131c; border: 1px solid rgba(255,255,255,0.12);',
  '  border-radius: 8px; color: #e8ecf3; outline: none;',
  '  transition: border-color 0.15s, box-shadow 0.15s;',
  '}',
  '.ctl-row input[type=text]:focus { border-color: #22c55e; box-shadow: 0 0 0 3px rgba(34,197,94,0.18); }',
  '.ctl-row input.ctl-invalido { border-color: #ef4444; box-shadow: 0 0 0 3px rgba(239,68,68,0.15); }',
  '.ctl-label { position: relative; }',
  '.ctl-badge {',
  '  position: absolute; top: -7px; right: 8px; font-size: 9px; padding: 1px 7px;',
  '  background: #1e293b; color: #94a3b8; border-radius: 999px; border: 1px solid rgba(255,255,255,0.1);',
  '}',
  '.ctl-keywrap { display: flex; gap: 6px; }',
  '.ctl-keywrap input { flex: 1; min-width: 0; font-family: Consolas, monospace; text-transform: lowercase; }',
  '.btn.captura { padding: 9px 11px; font-size: 14px; flex: none; background: rgba(167,139,250,0.15); border-color: rgba(167,139,250,0.35); color: #c4b5fd; }',
  '.btn.captura:hover { background: rgba(167,139,250,0.25); }',
  '.btn.captura.ativa { background: rgba(34,197,94,0.25); border-color: #22c55e; color: #86efac; animation: pulsar-captura 1.1s infinite; }',
  '@keyframes pulsar-captura { 50% { opacity: 0.55; } }',
  '.ctl-fim { display: flex; gap: 10px; align-items: center; }',
  '.ctl-hold { display: flex; gap: 5px; align-items: center; font-size: 12px; color: #aab5c6; cursor: pointer; white-space: nowrap; user-select: none; }',
  '.ctl-hold input { cursor: pointer; }',
  '.btn.lixo { padding: 8px 10px; color: #fca5a5; font-size: 13px; }',
  '.btn.lixo:hover { background: rgba(239,68,68,0.15); }',
  '.ctl-aliases { font-size: 12.5px !important; }',
  '.ctl-vazio { color: #77839a; font-size: 13px; padding: 14px 2px; }',
  '.linha-modelo { display: flex; gap: 10px; }',
  '.linha-modelo select { flex: 1; }',
  '.badge-personalizado {',
  '  display: none; font-size: 11px; padding: 3px 10px; border-radius: 999px;',
  '  background: rgba(250,204,21,0.12); color: #fde68a; border: 1px solid rgba(250,204,21,0.3);',
  '  margin-left: 8px; vertical-align: middle;',
  '}',
  '@media (max-width: 640px) {',
  '  .linha { flex-direction: column; gap: 0; } body { padding-bottom: 150px; }',
  '  .ctl-cab { display: none; }',
  '  .ctl-row { grid-template-columns: 1fr 1fr; }',
  '  .ctl-row .switch { grid-column: 1 / -1; }',
  '}',
  '</style>',
  '</head>',
  '<body>',
  '<div class="wrap">',
  '  <header>',
  '    <h1>🎮 CHAT<span class="pkm">PLAYS</span></h1>',
  '    <div class="sub">Assistente de configuração — o que você salvou já vem preenchido</div>',
  '    <div class="versao" id="versao">v?</div>',
  '  </header>',
  '',
  '  <div class="erros-gerais" id="erros-gerais"></div>',
  '',
  '  <div id="tela-form">',
  '',
  '  <div class="card" id="card-twitch">',
  '    <div class="card-top">',
  '      <h2>🟣 Twitch <span class="badge-plat">chat da sua live Twitch</span></h2>',
  '      <label class="switch"><input type="checkbox" id="tg-twitch" checked><span class="trilho"></span><span class="bola"></span></label>',
  '    </div>',
  '    <div class="linha">',
  '      <div class="campo">',
  '        <label for="f-usuario">Usuário do bot</label>',
  '        <input id="f-usuario" placeholder="ex.: meu_bot_zueiro" autocomplete="off">',
  '        <div class="dica">Crie uma <b>segunda conta</b> Twitch para o bot (não use a sua).</div>',
  '      </div>',
  '      <div class="campo">',
  '        <label for="f-canal">Canal que o bot monitora</label>',
  '        <input id="f-canal" placeholder="ex.: sindromegames" autocomplete="off">',
  '        <div class="dica">É o canal onde VOCÊ transmite (sem o #).</div>',
  '      </div>',
  '    </div>',
  '    <div class="campo rel">',
  '      <label for="f-token">Token OAuth do bot</label>',
  '      <input id="f-token" type="password" placeholder="oauth:..." autocomplete="off">',
  '      <button class="olho" id="olho-token" type="button" title="mostrar/ocultar">👁</button>',
  '      <div class="hint-salvo" id="hint-token">✔ há um token salvo — deixe como está para manter (apague e salve para remover)</div>',
  '      <div class="dica">Gere em <a href="https://twitchtokengenerator.com/" target="_blank" rel="noopener">twitchtokengenerator.com</a> → botão <b>Bot Chat Token</b> → copie o <b>Access token</b>. Cole com ou sem o "oauth:".</div>',
  '    </div>',
  '    <div class="acoes-plat">',
  '      <button class="btn teste" id="btn-twitch" type="button">🔌 Testar Twitch</button>',
  '      <div class="res" id="res-twitch"></div>',
  '    </div>',
  '  </div>',
  '',
  '  <div class="card" id="card-youtube">',
  '    <div class="card-top">',
  '      <h2>🔴 YouTube <span class="badge-plat">chat da sua live YouTube</span></h2>',
  '      <label class="switch"><input type="checkbox" id="tg-youtube"><span class="trilho"></span><span class="bola"></span></label>',
  '    </div>',
  '    <div class="campo rel">',
  '      <label for="f-ytkey">Chave de API do YouTube</label>',
  '      <input id="f-ytkey" type="password" placeholder="AIza..." autocomplete="off">',
  '      <button class="olho" id="olho-ytkey" type="button" title="mostrar/ocultar">👁</button>',
  '      <div class="hint-salvo" id="hint-ytkey">✔ há uma chave salva — deixe como está para manter (apague e salve para remover)</div>',
  '      <div class="dica">Crie grátis no <a href="https://console.cloud.google.com/" target="_blank" rel="noopener">Google Cloud Console</a>: crie um projeto → ative a <b>YouTube Data API v3</b> → Credenciais → Chave de API.</div>',
  '    </div>',
  '    <div class="campo">',
  '      <label for="f-ytvideo">ID ou URL da live</label>',
  '      <input id="f-ytvideo" placeholder="ex.: jfKfPfyJRdk ou https://youtube.com/watch?v=..." autocomplete="off">',
  '      <div class="hint-id" id="hint-video"></div>',
  '      <div class="dica">Cole o endereço da live direto do navegador — o bot extrai o ID sozinho. Cada live nova tem um ID novo.</div>',
  '    </div>',
  '    <div class="acoes-plat">',
  '      <button class="btn teste" id="btn-youtube" type="button">🔌 Testar YouTube</button>',
  '      <div class="res" id="res-youtube"></div>',
  '    </div>',
  '  </div>',
  '',
  '  <div class="card" id="card-jogo">',
  '    <div class="card-top">',
  '      <h2>🎮 Jogo / Emulador <span class="badge-plat">o programa que o chat vai controlar</span></h2>',
  '    </div>',
  '    <div class="campo caminho">',
  '      <label for="f-exe">Caminho do executável (o jogo que o bot abre e controla)</label>',
  '      <input id="f-exe" placeholder="C:\\Users\\Admin\\Downloads\\visualboyadvance-m-Win-x86_64\\visualboyadvance-m.exe" autocomplete="off" spellcheck="false">',
  '      <div class="dica">Cola o caminho completo do <b>.exe</b> (clique direito no arquivo → “Copiar como caminho”). Serve <b>qualquer programa</b>: VBA-M, mGBA, RetroArch, DeSmuME, Minecraft… Se já estiver aberto, o bot só vigia (não abre 2º).</div>',
  '    </div>',
  '    <div class="campo caminho">',
  '      <label for="f-rom">ROM do jogo (só se for emulador)</label>',
  '      <input id="f-rom" placeholder="C:\\Users\\Admin\\Downloads\\Pokemon - Esmeralda.gba" autocomplete="off" spellcheck="false">',
  '      <div class="dica">O bot abre o emulador <b>já com essa ROM</b> — e se o jogo fechar no meio da live, reabre com a <b>mesma ROM</b>. Deixa vazio para jogos sem ROM (Minecraft etc.).</div>',
  '    </div>',
  '    <div class="linha-toggle">',
  '      <div>',
  '        <div class="titulo">🔄 Reabrir o jogo se ele fechar</div>',
  '        <div class="sub">Fechou/c rash no meio da live? O bot reabre sozinho com a mesma ROM (até 5 quedas seguidas — depois avisa e para).</div>',
  '      </div>',
  '      <label class="switch"><input type="checkbox" id="tg-reabrir" checked><span class="trilho"></span><span class="bola"></span></label>',
  '    </div>',
  '    <div class="acoes-plat">',
  '      <button class="btn teste" id="btn-verificar-jogo" type="button">🔍 Verificar caminhos</button>',
  '      <button class="btn" id="btn-abrir-jogo" type="button">▶ Abrir agora</button>',
  '      <div class="res" id="res-jogo"></div>',
  '    </div>',
  '  </div>',
  '',
  '  <div class="card" id="card-controles">',
  '    <div class="card-top">',
  '      <h2>🎮 Controles do Chat <span class="badge-plat">o que o chat digita → qual tecla o bot aperta</span><span class="badge-personalizado" id="badge-personalizado">✏️ Personalizado</span></h2>',
  '    </div>',
  '    <div class="campo">',
  '      <label for="f-modelo">Modelo de controles (ponto de partida)</label>',
  '      <div class="linha-modelo">',
  '        <select id="f-modelo">',
  '          <option value="vbam">VisualBoyAdvance-M (Game Boy)</option>',
  '          <option value="mgba">mGBA (Game Boy)</option>',
  '          <option value="desmume">DeSmuME (Nintendo DS)</option>',
  '          <option value="retroarch">RetroArch</option>',
  '          <option value="personalizado" disabled>Personalizado (editado)</option>',
  '        </select>',
  '        <button class="btn teste" id="btn-aplicar-modelo" type="button">↺ Aplicar modelo</button>',
  '      </div>',
  '      <div class="dica">Aplicar um modelo <b>substitui</b> a lista abaixo pelos controles padrão dele — depois é só editar à vontade (adicionar Pular, Inventário...). Os modelos são só o começo, não o limite.</div>',
  '    </div>',
  '    <div id="lista-controles"></div>',
  '    <div class="acoes-plat">',
  '      <button class="btn teste" id="btn-add-controle" type="button">+ Adicionar controle</button>',
  '      <div class="res" id="res-controles"></div>',
  '    </div>',
  '    <div class="dica">Cada linha: <b>ação</b> → <b>tecla</b> do teclado → <b>palavras</b> que o chat digita (separadas por vírgula). ⌨ captura a tecla que você apertar. Conflitos de palavra aparecem aqui antes de salvar.</div>',
  '  </div>',
  '',
  '  <div class="card" id="card-testar-comando">',
  '    <div class="card-top">',
  '      <h2>🧪 Testar Comandos <span class="badge-plat">simulação segura antes da live</span></h2>',
  '    </div>',
  '    <div class="campo">',
  '      <label for="f-teste-comando">Digite exatamente o que alguém escreveria no chat</label>',
  '      <input id="f-teste-comando" placeholder="ex.: cima, hold direita 2, mouse esquerda, pad a, dialogo, !comandos" autocomplete="off" spellcheck="false">',
  '      <div class="dica"><b>Não envia nenhuma tecla, clique ou gamepad para o jogo.</b> Apenas mostra como o ChatPlays interpretaria a mensagem. Também testa os aliases que você acabou de editar, mesmo antes de salvar.</div>',
  '      <div class="cmd-exemplos">',
  '        <button class="cmd-chip" type="button" data-cmd="cima">cima</button>',
  '        <button class="cmd-chip" type="button" data-cmd="hold direita 2">hold direita 2</button>',
  '        <button class="cmd-chip" type="button" data-cmd="mouse esquerda">mouse esquerda</button>',
  '        <button class="cmd-chip" type="button" data-cmd="pad a">pad a</button>',
  '        <button class="cmd-chip" type="button" data-cmd="dialogo">dialogo</button>',
  '        <button class="cmd-chip" type="button" data-cmd="!comandos">!comandos</button>',
  '      </div>',
  '    </div>',
  '    <div class="acoes-plat">',
  '      <button class="btn teste" id="btn-testar-comando" type="button">🧪 Testar sem executar</button>',
  '      <div class="res" id="res-teste-comando"></div>',
  '    </div>',
  '  </div>',
  '',
  '  <details class="avancado">',
  '    <summary>Avançado (opcional — já vem bom por padrão)</summary>',
  '    <div class="card">',
  '      <div class="linha">',
  '        <div class="campo">',
  '          <label for="f-cooldown">Cooldown por pessoa (ms)</label>',
  '          <input id="f-cooldown" type="number" min="0" step="100">',
  '          <div class="dica">Tempo mínimo entre comandos do MESMO espectador.</div>',
  '        </div>',
  '        <div class="campo">',
  '          <label for="f-duracao">Duração da tecla (ms)</label>',
  '          <input id="f-duracao" type="number" min="50" step="10">',
  '          <div class="dica">Quanto tempo cada tecla fica apertada no jogo.</div>',
  '        </div>',
  '      </div>',
  '      <div class="linha">',
  '        <div class="campo">',
  '          <label for="f-modo-inicial">Modo inicial</label>',
  '          <select id="f-modo-inicial">',
  '            <option value="anarquia">Anarquia (tudo executa na hora)</option>',
  '            <option value="democracia">Democracia (o mais votado executa)</option>',
  '          </select>',
  '        </div>',
  '        <div class="campo">',
  '          <label for="f-tecla-pausa">Tecla de pausa (streamer)</label>',
  '          <input id="f-tecla-pausa" placeholder="f9">',
  '          <div class="dica">Pausa/libera o chat na hora (evite teclas que o emulador usa).</div>',
  '        </div>',
  '      </div>',
  '      <div class="campo">',
  '          <label for="f-modo-teclado">Teclado</label>',
  '          <select id="f-modo-teclado">',
  '            <option value="janela">Janela (teclas só no emulador) — recomendado</option>',
  '            <option value="global">Global (teclas na janela em foco)</option>',
  '          </select>',
  '        </div>',
  '      </div>',
  '    </div>',
  '  </details>',
  '',
  '  </div><!-- /tela-form -->',
  '',
  '  <div id="tela-sucesso">',
  '    <div class="emoji">🎉</div>',
  '    <h2 id="sucesso-titulo">Configuração salva!</h2>',
  '    <p id="sucesso-txt"></p>',
  '    <div class="passos" id="sucesso-passos"></div>',
  '    <button class="btn primario" id="btn-fechar" type="button">Fechar assistente</button>',
  '  </div>',
  '',
  '</div>',
  '',
  '<div class="barra-fix">',
  '  <div class="dentro">',
  '    <button class="btn primario" id="btn-salvar" type="button" disabled>💾 Salvar e continuar</button>',
  '    <button class="btn" id="btn-iniciar" type="button">▶ Iniciar sem salvar</button>',
  '    <button class="btn fantasma" id="btn-sair" type="button">Sair sem salvar</button>',
  '    <div class="status" id="status"><span class="pt"></span><span id="status-txt">carregando...</span></div>',
  '  </div>',
  '</div>',
  '',
  '<script>',
  'var ROTULO_SALVAR = "💾 Salvar e continuar";',
  'function $(id) { return document.getElementById(id); }',
  'function txt(el, mensagem) { el.textContent = mensagem; }',
  '',
  'function api(caminho, corpo) {',
  '  var op = corpo ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(corpo) } : {};',
  '  return fetch(caminho, op).then(function (r) { return r.json(); });',
  '}',
  '',
  'function mostrarRes(el, classe, mensagem) {',
  '  el.className = "res " + classe;',
  '  txt(el, mensagem);',
  '}',
  '',
  'function alternarCard(idToggle, idCard) {',
  '  var ativo = $(idToggle).checked;',
  '  $(idCard).className = ativo ? "card" : "card inativo";',
  '}',
  '',
  'function botaoCarregando(btn, carregando, rotulo) {',
  '  if (carregando) { btn.disabled = true; btn.innerHTML = \'<span class="spinner"></span>\' + rotulo; }',
  '  else { btn.disabled = false; btn.textContent = rotulo; }',
  '}',
  '',
  'function detectarId(valor) {',
  '  var bruto = String(valor || "").trim();',
  '  if (!bruto) return "";',
  '  if (bruto.indexOf("/") === -1 && bruto.indexOf("?") === -1) return "";',
  '  var m = bruto.match(/[?&]v=([A-Za-z0-9_-]{5,})/);',
  '  if (m) return m[1];',
  '  m = bruto.match(/youtu\\.be\\/([A-Za-z0-9_-]{5,})/);',
  '  if (m) return m[1];',
  '  m = bruto.match(/youtube\\.com\\/(?:live|shorts|embed)\\/([A-Za-z0-9_-]{5,})/);',
  '  if (m) return m[1];',
  '  return "";',
  '}',
  '',
  '// ---- v2.9: Controles do Chat (registro editável no navegador) ----',
  'var CONTROLES = [];',
  'var RESERVADOS = [];',
  'var TECLAS_VALIDAS = [];',
  'var MODELOS = {};',
  'var EDITOU_CONTROLES = false;',
  'var ORIGEM_CONTROLES = "env";',
  'var capturaAtiva = null; // { btn, input, modificador }',
  '',
  'function normalizarPalavra(t) {',
  '  return String(t || "").toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").replace(/\\s+/g, " ").trim();',
  '}',
  '',
  'function ehReservada(p) { return RESERVADOS.indexOf(p) !== -1; }',
  '',
  'function teclaValidaCliente(t) {',
  '  var partes = String(t || "").toLowerCase().split("+").map(function (p) { return p.trim(); });',
  '  if (!partes.length || partes.some(function (p) { return !p; })) return false;',
  '  for (var i = 0; i < partes.length; i++) {',
  '    if (TECLAS_VALIDAS.indexOf(partes[i]) === -1) return false;',
  '  }',
  '  var mods = ["shift", "ctrl", "alt"];',
  '  for (var j = 0; j < partes.length - 1; j++) {',
  '    if (mods.indexOf(partes[j]) === -1) return false;',
  '  }',
  '  return !(partes.length > 1 && mods.indexOf(partes[partes.length - 1]) !== -1);',
  '}',
  '',
  '// tecla física → nome canônico do bot (Space → space, Shift+F5 → shift+f5)',
  'function teclaDoEvento(e) {',
  '  var k = e.key;',
  '  if (!k) return null;',
  '  if (k === " ") return "space";',
  '  var mapa = { Enter: "enter", Escape: "esc", Tab: "tab", Backspace: "backspace",',
  '    ArrowUp: "up", ArrowDown: "down", ArrowLeft: "left", ArrowRight: "right",',
  '    Shift: "shift", Control: "ctrl", Alt: "alt" };',
  '  if (mapa[k]) return mapa[k];',
  '  if (/^[a-z]$/i.test(k)) return k.toLowerCase();',
  '  if (/^[0-9]$/.test(k)) return k;',
  '  if (/^F([1-9]|1[0-2])$/.test(k)) return k.toLowerCase();',
  '  return null;',
  '}',
  '',
  'function teclaCompleta(e) {',
  '  var principal = teclaDoEvento(e);',
  '  if (principal === null) return null;',
  '  var mods = ["shift", "ctrl", "alt"];',
  '  if (mods.indexOf(principal) !== -1) return principal;',
  '  var partes = [];',
  '  if (e.ctrlKey) partes.push("ctrl");',
  '  if (e.altKey) partes.push("alt");',
  '  if (e.shiftKey) partes.push("shift");',
  '  partes.push(principal);',
  '  return partes.join("+");',
  '}',
  '',
  'function iniciarCaptura(btn, input) {',
  '  if (capturaAtiva) pararCaptura();',
  '  capturaAtiva = { btn: btn, input: input, modificador: null };',
  '  btn.classList.add("ativa");',
  '  txt(btn, "…");',
  '  window.addEventListener("keydown", aoApertarTecla, true);',
  '  window.addEventListener("keyup", aoSoltarTecla, true);',
  '  window.addEventListener("blur", pararCaptura);',
  '}',
  '',
  'function pararCaptura() {',
  '  if (!capturaAtiva) return;',
  '  window.removeEventListener("keydown", aoApertarTecla, true);',
  '  window.removeEventListener("keyup", aoSoltarTecla, true);',
  '  window.removeEventListener("blur", pararCaptura);',
  '  capturaAtiva.btn.classList.remove("ativa");',
  '  txt(capturaAtiva.btn, "⌨");',
  '  capturaAtiva = null;',
  '}',
  '',
  'function concluirCaptura(tecla) {',
  '  var input = capturaAtiva.input;',
  '  pararCaptura();',
  '  input.value = tecla;',
  '  input.dispatchEvent(new Event("input"));',
  '}',
  '',
  'function aoSoltarTecla(e) {',
  '  if (!capturaAtiva || !capturaAtiva.modificador || teclaDoEvento(e) !== capturaAtiva.modificador) return;',
  '  e.preventDefault();',
  '  e.stopPropagation();',
  '  concluirCaptura(capturaAtiva.modificador);',
  '}',
  '',
  'function aoApertarTecla(e) {',
  '  if (!capturaAtiva) return;',
  '  e.preventDefault();',
  '  e.stopPropagation();',
  '  var t = teclaCompleta(e);',
  '  if (t === null) {',
  '    mostrarRes($("res-controles"), "err", "✖ Essa tecla não é suportada (" + (e.key || "?") + ") — tente outra ou digite o nome (ex.: space, f5, shift+f5)");',
  '    pararCaptura();',
  '    return;',
  '  }',
  '  if (["shift", "ctrl", "alt"].indexOf(t) !== -1) {',
  '    capturaAtiva.modificador = t;',
  '    return;',
  '  }',
  '  concluirCaptura(t);',
  '}',
  '',
  'function renderControles() {',
  '  var alvo = $("lista-controles");',
  '  alvo.textContent = "";',
  '  if (!CONTROLES.length) {',
  '    var vazio = document.createElement("div");',
  '    vazio.className = "ctl-vazio";',
  '    txt(vazio, "Nenhum controle — aplique um modelo acima ou adicione do zero.");',
  '    alvo.appendChild(vazio);',
  '    return;',
  '  }',
  '  var cab = document.createElement("div");',
  '  cab.className = "ctl-cab";',
  '  var rotulos = ["ativo?", "Ação (o que faz)", "Tecla do teclado", "Palavras que o chat digita", ""];',
  '  for (var r = 0; r < rotulos.length; r++) {',
  '    var cc = document.createElement("div");',
  '    txt(cc, rotulos[r]);',
  '    cab.appendChild(cc);',
  '  }',
  '  alvo.appendChild(cab);',
  '  for (var i = 0; i < CONTROLES.length; i++) alvo.appendChild(criarLinhaControle(i));',
  '}',
  '',
  'function criarLinhaControle(i) {',
  '  var c = CONTROLES[i];',
  '  var linha = document.createElement("div");',
  '  linha.className = "ctl-row" + (c.enabled ? "" : " off");',
  '',
  '  // 1) toggle ativo',
  '  var sw = document.createElement("label");',
  '  sw.className = "switch";',
  '  var cbAtivo = document.createElement("input");',
  '  cbAtivo.type = "checkbox";',
  '  cbAtivo.checked = c.enabled !== false;',
  '  cbAtivo.addEventListener("change", function () {',
  '    c.enabled = cbAtivo.checked;',
  '    linha.className = "ctl-row" + (c.enabled ? "" : " off");',
  '    EDITOU_CONTROLES = true;',
  '    validarControlesCliente();',
  '  });',
  '  var trilho = document.createElement("span"); trilho.className = "trilho";',
  '  var bola = document.createElement("span"); bola.className = "bola";',
  '  sw.appendChild(cbAtivo); sw.appendChild(trilho); sw.appendChild(bola);',
  '  linha.appendChild(sw);',
  '',
  '  // 2) nome da ação',
  '  var wrapLabel = document.createElement("div");',
  '  wrapLabel.className = "ctl-label";',
  '  var inpLabel = document.createElement("input");',
  '  inpLabel.type = "text";',
  '  inpLabel.maxLength = 30;',
  '  inpLabel.placeholder = c.builtin ? "" : "ação (ex.: Pular)";',
  '  inpLabel.value = c.label || "";',
  '  inpLabel.autocomplete = "off";',
  '  inpLabel.addEventListener("input", function () {',
  '    c.label = inpLabel.value;',
  '    EDITOU_CONTROLES = true;',
  '    sugerirAliases(i);',
  '    validarControlesCliente();',
  '  });',
  '  wrapLabel.appendChild(inpLabel);',
  '  if (c.builtin) {',
  '    var badge = document.createElement("span");',
  '    badge.className = "ctl-badge";',
  '    txt(badge, "padrão");',
  '    wrapLabel.appendChild(badge);',
  '  }',
  '  linha.appendChild(wrapLabel);',
  '',
  '  // 3) tecla + captura',
  '  var wrapKey = document.createElement("div");',
  '  wrapKey.className = "ctl-keywrap";',
  '  var inpKey = document.createElement("input");',
  '  inpKey.type = "text";',
  '  inpKey.placeholder = "tecla (ex.: space)";',
  '  inpKey.value = c.key || "";',
  '  inpKey.autocomplete = "off";',
  '  inpKey.spellcheck = false;',
  '  inpKey.addEventListener("input", function () {',
  '    c.key = inpKey.value.toLowerCase();',
  '    EDITOU_CONTROLES = true;',
  '    sugerirAliases(i);',
  '    validarControlesCliente();',
  '  });',
  '  var btnCap = document.createElement("button");',
  '  btnCap.type = "button";',
  '  btnCap.className = "btn captura";',
  '  btnCap.title = "capturar a próxima tecla apertada";',
  '  txt(btnCap, "⌨");',
  '  btnCap.addEventListener("click", function () {',
  '    if (capturaAtiva && capturaAtiva.input === inpKey) { pararCaptura(); return; }',
  '    iniciarCaptura(btnCap, inpKey);',
  '  });',
  '  wrapKey.appendChild(inpKey);',
  '  wrapKey.appendChild(btnCap);',
  '  linha.appendChild(wrapKey);',
  '',
  '  // 4) palavras do chat',
  '  var inpAliases = document.createElement("input");',
  '  inpAliases.type = "text";',
  '  inpAliases.className = "ctl-aliases";',
  '  inpAliases.placeholder = "ex.: pular, pulo, jump";',
  '  inpAliases.value = (c.aliases || []).join(", ");',
  '  inpAliases.autocomplete = "off";',
  '  inpAliases.spellcheck = false;',
  '  inpAliases.dataset.tocado = "nao";',
  '  inpAliases.addEventListener("input", function () {',
  '    inpAliases.dataset.tocado = "sim";',
  '    c.aliases = inpAliases.value.split(",").map(function (a) { return normalizarPalavra(a); }).filter(Boolean);',
  '    EDITOU_CONTROLES = true;',
  '    validarControlesCliente();',
  '  });',
  '  linha.appendChild(inpAliases);',
  '',
  '  // 5) hold + remover',
  '  var fim = document.createElement("div");',
  '  fim.className = "ctl-fim";',
  '  var lblHold = document.createElement("label");',
  '  lblHold.className = "ctl-hold";',
  '  var cbHold = document.createElement("input");',
  '  cbHold.type = "checkbox";',
  '  cbHold.checked = c.holdable !== false;',
  '  cbHold.title = "o chat pode SEGURAR esta tecla (hold)";',
  '  cbHold.addEventListener("change", function () {',
  '    c.holdable = cbHold.checked;',
  '    EDITOU_CONTROLES = true;',
  '  });',
  '  var txtHold = document.createElement("span");',
  '  txt(txtHold, "hold");',
  '  lblHold.appendChild(cbHold);',
  '  lblHold.appendChild(txtHold);',
  '  fim.appendChild(lblHold);',
  '  if (!c.builtin) {',
  '    var btnLixo = document.createElement("button");',
  '    btnLixo.type = "button";',
  '    btnLixo.className = "btn lixo";',
  '    btnLixo.title = "remover este controle";',
  '    txt(btnLixo, "✕");',
  '    btnLixo.addEventListener("click", function () {',
  '      CONTROLES.splice(i, 1);',
  '      EDITOU_CONTROLES = true;',
  '      renderControles();',
  '      validarControlesCliente();',
  '    });',
  '    fim.appendChild(btnLixo);',
  '  }',
  '  linha.appendChild(fim);',
  '',
  '  c.__inpLabel = inpLabel;',
  '  c.__inpKey = inpKey;',
  '  c.__inpAliases = inpAliases;',
  '  return linha;',
  '}',
  '',
  '// sugere palavras quando o usuário ainda não digitou nenhuma',
  'function sugerirAliases(i) {',
  '  var c = CONTROLES[i];',
  '  if (!c || !c.key || !c.label) return;',
  '  if (c.__inpAliases && c.__inpAliases.dataset.tocado === "sim") return;',
  '  if ((c.aliases || []).length > 0) return;',
  '  api("/api/gerar-aliases", { chave: String(c.key).toLowerCase(), rotulo: c.label }).then(function (r) {',
  '    if (!r.aliases || !r.aliases.length) return;',
  '    if (c.__inpAliases && c.__inpAliases.dataset.tocado === "sim") return;',
  '    if ((c.aliases || []).length > 0) return;',
  '    c.aliases = r.aliases;',
  '    if (c.__inpAliases) c.__inpAliases.value = r.aliases.join(", ");',
  '    validarControlesCliente();',
  '  }).catch(function () {});',
  '}',
  '',
  '// validação no navegador (o servidor REPETE tudo antes de gravar)',
  'function validarControlesCliente() {',
  '  var res = $("res-controles");',
  '  var erros = [];',
  '  var dono = Object.create(null); // palavra → índice (sem protótipo: "constructor" não engana)',
  '  var ativos = 0;',
  '  for (var i = 0; i < CONTROLES.length; i++) {',
  '    var c = CONTROLES[i];',
  '    var marcaLabel = false, marcaKey = false, marcaAlias = false;',
  '    var nome = (c.label || "(sem nome)").trim();',
  '    if (!c.label) { if (c.enabled !== false) erros.push(nome + ": falta o nome da ação"); marcaLabel = true; }',
  '    if (!c.key) { erros.push(nome + ": falta a tecla do teclado"); marcaKey = true; }',
  '    else if (!teclaValidaCliente(c.key)) { erros.push(nome + ": tecla \\"" + c.key + "\\" não suportada"); marcaKey = true; }',
  '    var aliases = (c.aliases || []).map(normalizarPalavra).filter(Boolean);',
  '    var validos = [];',
  '    for (var a = 0; a < aliases.length; a++) {',
  '      var p = aliases[a];',
  '      if (!/^[a-z0-9]+( [a-z0-9]+)*$/.test(p)) { erros.push(nome + ": palavra \\"" + p + "\\" tem caracteres estranhos"); marcaAlias = true; continue; }',
  '      if (ehReservada(p)) { erros.push(nome + ": \\"" + p + "\\" é palavra do sistema (hold, soltar, !comandos...)"); marcaAlias = true; continue; }',
  '      if (dono[p] !== undefined && dono[p] !== i) {',
  '        var donoC = CONTROLES[dono[p]];',
  '        if (donoC.enabled !== false && c.enabled !== false) { erros.push("palavra \\"" + p + "\\" repetida em " + donoC.label + " e " + nome); marcaAlias = true; continue; }',
  '        if (c.enabled === false) { validos.push(p); continue; } // desativado mantém a palavra, sem tomar a titularidade',
  '      }',
  '      dono[p] = i; // ativo assume a titularidade: o próximo ATIVO que pedir a mesma palavra esbarra aqui',
  '      validos.push(p);',
  '    }',
  '    if (c.enabled !== false) {',
  '      ativos++;',
  '      if (!validos.length) { erros.push(nome + " está ativo sem NENHUMA palavra de chat"); marcaAlias = true; }',
  '    }',
  '    if (c.__inpLabel) c.__inpLabel.className = marcaLabel ? "ctl-invalido" : "";',
  '    if (c.__inpKey) c.__inpKey.className = marcaKey ? "ctl-invalido" : "";',
  '    if (c.__inpAliases) c.__inpAliases.className = "ctl-aliases" + (marcaAlias ? " ctl-invalido" : "");',
  '  }',
  '  if (erros.length) mostrarRes(res, "err", "✖ " + erros[0] + (erros.length > 1 ? " (e mais " + (erros.length - 1) + ")" : ""));',
  '  else mostrarRes(res, "ok", "✔ " + ativos + " controle(s) ativos prontos — valem para Twitch e YouTube");',
  '  return erros.length === 0;',
  '}',
  '',
  'function adicionarControle() {',
  '  CONTROLES.push({ id: "", label: "", key: "", aliases: [], holdable: true, builtin: false, enabled: true });',
  '  EDITOU_CONTROLES = true;',
  '  renderControles();',
  '  var linhas = document.querySelectorAll(".ctl-row");',
  '  if (linhas.length) {',
  '    var ultimo = linhas[linhas.length - 1].querySelector("input[type=text]");',
  '    if (ultimo) ultimo.focus();',
  '  }',
  '  validarControlesCliente();',
  '}',
  '',
  'function aplicarModelo() {',
  '  var sel = $("f-modelo").value;',
  '  var nomes = { vbam: "VBA-M", mgba: "mGBA", desmume: "DeSmuME", retroarch: "RetroArch" };',
  '  if (!MODELOS[sel]) { mostrarRes($("res-controles"), "err", "✖ Escolha um modelo para aplicar"); return; }',
  '  if (!window.confirm("Aplicar o modelo " + (nomes[sel] || sel) + "? A lista atual (inclusive controles personalizados) será substituída.")) return;',
  '  CONTROLES = MODELOS[sel].map(function (c) { return { id: c.id, label: c.label, icone: c.icone, key: c.key, aliases: c.aliases.slice(), holdable: c.holdable, builtin: c.builtin, enabled: true }; });',
  '  EDITOU_CONTROLES = false; // voltou exatamente ao modelo',
  '  renderControles();',
  '  validarControlesCliente();',
  '}',
  '',
  'function atualizarBadgeModelo() {',
  '  var badge = $("badge-personalizado");',
  '  if (!badge) return;',
  '  var sel = $("f-modelo");',
  '  var personalizado = EDITOU_CONTROLES || ORIGEM_CONTROLES === "arquivo" || !CONTROLES.length;',
  '  badge.style.display = personalizado ? "inline-block" : "none";',
  '  if (personalizado) sel.value = "personalizado";',
  '}',
  '',
  'function carregarControles(d) {',
  '  RESERVADOS = d.reservados || [];',
  '  TECLAS_VALIDAS = d.teclasValidas || [];',
  '  MODELOS = d.modelos || {};',
  '  ORIGEM_CONTROLES = d.origemControles || "env";',
  '  CONTROLES = (d.controles || []).map(function (c) {',
  '    return { id: c.id, label: c.label, icone: c.icone, key: c.key, aliases: (c.aliases || []).slice(), holdable: c.holdable, builtin: c.builtin, enabled: c.enabled };',
  '  });',
  '  EDITOU_CONTROLES = false;',
  '  renderControles();',
  '  validarControlesCliente();',
  '  atualizarBadgeModelo();',
  '}',
  '',
  'function carregar() {',
  '  api("/api/estado").then(function (d) {',
  '    txt($("versao"), "v" + d.versao);',
  '    $("tg-twitch").checked = d.twitchAtivo;',
  '    $("tg-youtube").checked = d.youtubeAtivo;',
  '    alternarCard("tg-twitch", "card-twitch");',
  '    alternarCard("tg-youtube", "card-youtube");',
  '    var v = d.valores || {};',
  '    $("f-usuario").value = v.TWITCH_BOT_USERNAME || "";',
  '    $("f-canal").value = v.TWITCH_CHANNEL || "";',
  '    $("f-ytvideo").value = v.YOUTUBE_VIDEO_ID || "";',
  '    $("f-cooldown").value = v.COMMAND_COOLDOWN_MS || 1500;',
  '    $("f-duracao").value = v.KEY_PRESS_DURATION_MS || 230;',
  '    $("f-modo-inicial").value = v.MODO_INICIAL || "anarquia";',
  '    $("f-tecla-pausa").value = v.TECLA_PAUSA || "f9";',
  '    $("f-modo-teclado").value = v.MODO_TECLADO || "janela";',
  '    var modeloEnv = v.EMULADOR_PRESET || "vbam";',
  '    if (["vbam","mgba","desmume","retroarch"].indexOf(modeloEnv) === -1) modeloEnv = "vbam";',
  '    $("f-modelo").value = modeloEnv;',
  '    carregarControles(d);',
  '    $("f-exe").value = v.EMULADOR_EXE || "";',
  '    $("f-rom").value = v.JOGO_ROM || "";',
  '    $("tg-reabrir").checked = v.JOGO_AUTO_REINICIAR !== "false";',
  '    // v2.8.1: segredos voltam MASCARADOS (••••••••abcd) — o valor em claro',
  '    // nunca vai para o navegador; a máscara intacta no submit = manter',
  '    $("f-token").value = v.TWITCH_OAUTH_TOKEN || "";',
  '    $("f-ytkey").value = v.YOUTUBE_API_KEY || "";',
  '    var hintToken = $("hint-token");',
  '    if (hintToken) hintToken.style.display = v.temTokenTwitch ? "block" : "none";',
  '    var hintYtkey = $("hint-ytkey");',
  '    if (hintYtkey) hintYtkey.style.display = v.temChaveYoutube ? "block" : "none";',
  '    var st = $("status");',
  '    st.className = "status " + (d.configurado ? "on" : "");',
  '    txt($("status-txt"), d.configurado ? "configuração atual válida" : "configuração incompleta");',
  '    // v2.8: salvar só habilita depois do prefill carregar (campo vazio =',
  '    // apagar de verdade — sem prefill um salvar acidental limparia as chaves)',
  '    $("btn-salvar").disabled = false;',
  '    if (d.modo === "boot") {',
  '      ROTULO_SALVAR = "💾 Salvar e iniciar o bot";',
  '      txt($("btn-salvar"), ROTULO_SALVAR);',
  '      txt($("btn-sair"), "Sair sem iniciar");',
  '    } else {',
  '      $("btn-iniciar").style.display = "none";',
  '    }',
  '  }).catch(function () {',
  '    txt($("status-txt"), "sem contato com o bot");',
  '  });',
  '}',
  '',
  'function testarTwitch() {',
  '  var res = $("res-twitch");',
  '  res.className = "res";',
  '  botaoCarregando($("btn-twitch"), true, "Testando...");',
  '  api("/api/testar-twitch", {',
  '    TWITCH_BOT_USERNAME: $("f-usuario").value,',
  '    TWITCH_OAUTH_TOKEN: $("f-token").value,',
  '    TWITCH_CHANNEL: $("f-canal").value',
  '  }).then(function (r) {',
  '    botaoCarregando($("btn-twitch"), false, "🔌 Testar Twitch");',
  '    mostrarRes(res, r.ok ? "ok" : "err", (r.ok ? "✔ " : "✖ ") + r.mensagem);',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-twitch"), false, "🔌 Testar Twitch");',
  '    mostrarRes(res, "err", "✖ Falha ao testar: " + e);',
  '  });',
  '}',
  '',
  'function testarYoutube() {',
  '  var res = $("res-youtube");',
  '  res.className = "res";',
  '  botaoCarregando($("btn-youtube"), true, "Testando...");',
  '  api("/api/testar-youtube", {',
  '    YOUTUBE_API_KEY: $("f-ytkey").value,',
  '    YOUTUBE_VIDEO_ID: $("f-ytvideo").value',
  '  }).then(function (r) {',
  '    botaoCarregando($("btn-youtube"), false, "🔌 Testar YouTube");',
  '    var classe = r.ok ? "ok" : (r.aguardando ? "aguardando" : "err");',
  '    mostrarRes(res, classe, (r.ok ? "✔ " : (r.aguardando ? "⏳ " : "✖ ")) + r.mensagem);',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-youtube"), false, "🔌 Testar YouTube");',
  '    mostrarRes(res, "err", "✖ Falha ao testar: " + e);',
  '  });',
  '}',
  '',
  'function testarJogo() {',
  '  var res = $("res-jogo");',
  '  res.className = "res";',
  '  botaoCarregando($("btn-verificar-jogo"), true, "Verificando...");',
  '  api("/api/verificar-jogo", {',
  '    EMULADOR_EXE: $("f-exe").value.trim(),',
  '    JOGO_ROM: $("f-rom").value.trim()',
  '  }).then(function (r) {',
  '    botaoCarregando($("btn-verificar-jogo"), false, "🔍 Verificar caminhos");',
  '    var vazio = !$("f-exe").value.trim() && !$("f-rom").value.trim();',
  '    mostrarRes(res, r.ok ? "ok" : "err", (r.ok ? (vazio ? "ℹ " : "✔ ") : "✖ ") + r.mensagem);',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-verificar-jogo"), false, "🔍 Verificar caminhos");',
  '    mostrarRes(res, "err", "✖ Falha ao verificar: " + e);',
  '  });',
  '}',
  '',
  'function abrirJogo() {',
  '  var res = $("res-jogo");',
  '  res.className = "res";',
  '  botaoCarregando($("btn-abrir-jogo"), true, "Abrindo...");',
  '  api("/api/abrir-jogo", {',
  '    EMULADOR_EXE: $("f-exe").value.trim(),',
  '    JOGO_ROM: $("f-rom").value.trim()',
  '  }).then(function (r) {',
  '    botaoCarregando($("btn-abrir-jogo"), false, "▶ Abrir agora");',
  '    mostrarRes(res, r.ok ? "ok" : "err", (r.ok ? "✔ " : "✖ ") + r.mensagem);',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-abrir-jogo"), false, "▶ Abrir agora");',
  '    mostrarRes(res, "err", "✖ Falha ao abrir: " + e);',
  '  });',
  '}',
  '',
  'function controlesParaTeste() {',
  '  return CONTROLES.map(function (c) {',
  '    return { id: c.id, label: String(c.label || "").trim(), key: String(c.key || "").toLowerCase(), aliases: c.aliases || [], holdable: c.holdable !== false, builtin: Boolean(c.builtin), enabled: c.enabled !== false, icone: c.icone || "🎮" };',
  '  });',
  '}',
  '',
  'function testarComandoChat() {',
  '  var entrada = $("f-teste-comando").value.trim();',
  '  var res = $("res-teste-comando");',
  '  if (!entrada) { mostrarRes(res, "err", "✖ Digite um comando para testar."); return; }',
  '  botaoCarregando($("btn-testar-comando"), true, "Testando...");',
  '  api("/api/testar-comando", { texto: entrada, controles: controlesParaTeste() }).then(function (r) {',
  '    botaoCarregando($("btn-testar-comando"), false, "🧪 Testar sem executar");',
  '    if (!r.ok) {',
  '      mostrarRes(res, "err", "✖ " + ((r.erros || []).join(String.fromCharCode(10) + "• ") || "Não foi possível testar."));',
  '      return;',
  '    }',
  '    if (!r.reconhecido) {',
  '      mostrarRes(res, "aguardando", "❔ Não reconhecido" + String.fromCharCode(10) + (r.resumo || "Nenhuma ação seria executada."));',
  '      return;',
  '    }',
  '    var linhas = [(r.executaria ? "✔ " : "ℹ ") + r.titulo, r.resumo];',
  '    for (var i = 0; i < (r.detalhes || []).length; i++) linhas.push("• " + r.detalhes[i]);',
  '    linhas.push(r.executaria ? "SIMULAÇÃO: executaria essa ação no jogo." : "SIMULAÇÃO: não envia input ao jogo.");',
  '    mostrarRes(res, r.executaria ? "ok" : "aguardando", linhas.join(String.fromCharCode(10)));',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-testar-comando"), false, "🧪 Testar sem executar");',
  '    mostrarRes(res, "err", "✖ Falha ao testar: " + e);',
  '  });',
  '}',
  '',
  'function salvar() {',
  '  var errosEl = $("erros-gerais");',
  '  errosEl.style.display = "none";',
  '  // v2.9: controles do chat — bloqueia o save com conflito visível',
  '  if (!validarControlesCliente()) {',
  '    errosEl.style.display = "block";',
  '    txt(errosEl, "Corrija os Controles do Chat antes de salvar (conflito ou palavra inválida).");',
  '    var card = document.getElementById("card-controles");',
  '    if (card) card.scrollIntoView({ behavior: "smooth", block: "center" });',
  '    return;',
  '  }',
  '  var modelo = $("f-modelo").value;',
  '  var preset = (["vbam", "mgba", "desmume", "retroarch"].indexOf(modelo) !== -1) ? modelo : "vbam";',
  '  botaoCarregando($("btn-salvar"), true, "Salvando...");',
  '  api("/api/salvar", {',
  '    twitchAtivo: $("tg-twitch").checked,',
  '    youtubeAtivo: $("tg-youtube").checked,',
  '    jogoAutoReiniciar: $("tg-reabrir").checked,',
  '    controles: CONTROLES.map(function (c) {',
  '      return { id: c.id, label: String(c.label || "").trim(), key: String(c.key || "").toLowerCase(), aliases: c.aliases || [], holdable: c.holdable !== false, builtin: Boolean(c.builtin), enabled: c.enabled !== false };',
  '    }),',
  '    TWITCH_BOT_USERNAME: $("f-usuario").value.trim(),',
  '    TWITCH_OAUTH_TOKEN: $("f-token").value.trim(),',
  '    TWITCH_CHANNEL: $("f-canal").value.trim(),',
  '    YOUTUBE_API_KEY: $("f-ytkey").value.trim(),',
  '    YOUTUBE_VIDEO_ID: $("f-ytvideo").value.trim(),',
  '    EMULADOR_EXE: $("f-exe").value.trim(),',
  '    JOGO_ROM: $("f-rom").value.trim(),',
  '    COMMAND_COOLDOWN_MS: $("f-cooldown").value,',
  '    KEY_PRESS_DURATION_MS: $("f-duracao").value,',
  '    MODO_INICIAL: $("f-modo-inicial").value,',
  '    TECLA_PAUSA: $("f-tecla-pausa").value.trim(),',
  '    MODO_TECLADO: $("f-modo-teclado").value,',
  '    EMULADOR_PRESET: preset',
  '  }).then(function (r) {',
  '    botaoCarregando($("btn-salvar"), false, ROTULO_SALVAR);',
  '    if (r.ok) {',
  '      $("tela-form").style.display = "none";',
  '      document.querySelector(".barra-fix").style.display = "none";',
  '      document.querySelector("details.avancado").style.display = "none";',
  '      $("tela-sucesso").style.display = "block";',
  '      txt($("sucesso-titulo"), "Configuração salva! 🎉");',
  '      var linhas = [];',
  '      var temJogo = r.jogo && r.jogo.exe;',
  '      if (r.controles) {',
  '        linhas.push("🎮 " + r.controles.quantidade + " controle(s) do chat salvos — valem para Twitch E YouTube (dados/controles.json)");',
  '      }',
  '      if (r.continuara) {',
  '        txt($("sucesso-txt"), "O bot já está continuando o boot — volte para a janela do terminal e aproveite a live!");',
  '        linhas.push("1. Volte para o terminal do bot (ele está subindo o Twitch/YouTube agora)");',
  '        if (temJogo) {',
  '          linhas.push("2. O bot abre o jogo " + r.jogo.nome + " sozinho" + (r.jogo.rom ? " com a ROM " + r.jogo.rom : "") + " — e reabre se fechar");',
  '          linhas.push("3. Diga pro chat digitar " + palavrasIniciais() + "... e assista a mágica 🎮");',
  '        } else {',
  '          linhas.push("2. Abra o emulador com o jogo (VisualBoyAdvance-M, mGBA...)");',
  '          linhas.push("3. Deixe o bot perguntar qual é o .exe do emulador — Enter mantém o salvo");',
  '          linhas.push("4. Diga pro chat digitar " + palavrasIniciais() + "... e assista a mágica 🎮");',
  '        }',
  '      } else {',
  '        txt($("sucesso-txt"), "Tudo pronto no .env — agora é só rodar o bot.");',
  '        linhas.push("1. Feche esta aba (ou clique no botão abaixo)");',
  '        linhas.push("2. Abra o iniciar.bat — revise e clique em Salvar e iniciar o bot");',
  '        if (temJogo) {',
  '          linhas.push("3. O bot abre o jogo " + r.jogo.nome + " sozinho" + (r.jogo.rom ? " com a ROM " + r.jogo.rom : "") + " — e reabre se fechar");',
  '        } else {',
  '          linhas.push("3. Abra o emulador com o jogo e siga as instruções do terminal");',
  '        }',
  '        linhas.push("4. Diga pro chat digitar " + palavrasIniciais() + "... e assista a mágica 🎮");',
  '      }',
  '      if (r.overlay) {',
  '        linhas.push("5. Overlay do OBS: " + r.overlay + " (Fontes → + → Navegador)");',
  '      }',
  '      var passos = $("sucesso-passos");',
  '      passos.textContent = "";',
  '      for (var i = 0; i < linhas.length; i++) {',
  '        var div = document.createElement("div");',
  '        txt(div, linhas[i]);',
  '        passos.appendChild(div);',
  '      }',
  '    } else {',
  '      errosEl.style.display = "block";',
  '      var lista = "Não foi possível salvar:";',
  '      for (var j = 0; j < (r.erros || []).length; j++) lista += "\\n• " + r.erros[j];',
  '      txt(errosEl, lista);',
  '      errosEl.style.whiteSpace = "pre-line";',
  '      window.scrollTo({ top: 0, behavior: "smooth" });',
  '    }',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-salvar"), false, ROTULO_SALVAR);',
  '    errosEl.style.display = "block";',
  '    txt(errosEl, "Falha ao salvar: " + e);',
  '  });',
  '}',
  '',
  'function palavrasIniciais() {',
  '  var palavras = [];',
  '  for (var i = 0; i < CONTROLES.length && palavras.length < 4; i++) {',
  '    var c = CONTROLES[i];',
  '    if (c.enabled === false) continue;',
  '    if (c.aliases && c.aliases.length) palavras.push(c.aliases[0]);',
  '  }',
  '  return palavras.length ? palavras.join(", ") : "!comandos";',
  '}',
  '',
  'function iniciarAgora() {',
  '  botaoCarregando($("btn-iniciar"), true, "Iniciando...");',
  '  api("/api/iniciar", {}).then(function (r) {',
  '    if (!r.ok) {',
  '      botaoCarregando($("btn-iniciar"), false, "▶ Iniciar sem salvar");',
  '      txt($("status-txt"), r.mensagem || "não disponível agora");',
  '      return;',
  '    }',
  '    $("tela-form").style.display = "none";',
  '    document.querySelector(".barra-fix").style.display = "none";',
  '    document.querySelector("details.avancado").style.display = "none";',
  '    $("tela-sucesso").style.display = "block";',
  '    txt($("sucesso-titulo"), "Bot iniciando! 🎮");',
  '    txt($("sucesso-txt"), "O bot seguiu o boot com a configuração atual — volte para a janela do terminal e aproveite a live!");',
  '    $("sucesso-passos").textContent = "";',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-iniciar"), false, "▶ Iniciar sem salvar");',
  '    txt($("status-txt"), "falha ao iniciar: " + e);',
  '  });',
  '}',
  '',
  'function sair() {',
  '  api("/api/encerrar", {}).then(function () {',
  '    $("tela-form").style.display = "none";',
  '    document.querySelector(".barra-fix").style.display = "none";',
  '    $("tela-sucesso").style.display = "block";',
  '    txt($("sucesso-titulo"), "Até mais! 👋");',
  '    txt($("sucesso-txt"), "Nada foi salvo — pode fechar esta aba.");',
  '    $("sucesso-passos").textContent = "";',
  '  }).catch(function () {});',
  '}',
  '',
  'document.addEventListener("DOMContentLoaded", function () {',
  '  carregar();',
  '  $("tg-twitch").addEventListener("change", function () { alternarCard("tg-twitch", "card-twitch"); });',
  '  $("tg-youtube").addEventListener("change", function () { alternarCard("tg-youtube", "card-youtube"); });',
  '  $("btn-twitch").addEventListener("click", testarTwitch);',
  '  $("btn-youtube").addEventListener("click", testarYoutube);',
  '  $("btn-verificar-jogo").addEventListener("click", testarJogo);',
  '  $("btn-abrir-jogo").addEventListener("click", abrirJogo);',
  '  $("btn-testar-comando").addEventListener("click", testarComandoChat);',
  '  $("f-teste-comando").addEventListener("keydown", function (e) { if (e.key === "Enter") testarComandoChat(); });',
  '  Array.prototype.forEach.call(document.querySelectorAll(".cmd-chip"), function (btn) {',
  '    btn.addEventListener("click", function () { $("f-teste-comando").value = btn.getAttribute("data-cmd") || ""; testarComandoChat(); });',
  '  });',
  '  $("btn-salvar").addEventListener("click", salvar);',
  '  $("btn-iniciar").addEventListener("click", iniciarAgora);',
  '  $("btn-sair").addEventListener("click", sair);',
  '  $("btn-fechar").addEventListener("click", function () { window.close(); });',
  '  $("olho-token").addEventListener("click", function () {',
  '    var t = $("f-token"); t.type = t.type === "password" ? "text" : "password";',
  '  });',
  '  $("olho-ytkey").addEventListener("click", function () {',
  '    var t = $("f-ytkey"); t.type = t.type === "password" ? "text" : "password";',
  '  });',
  '  $("f-ytvideo").addEventListener("input", function () {',
  '    var id = detectarId(this.value);',
  '    var hint = $("hint-video");',
  '    if (id) { hint.style.display = "block"; txt(hint, "ID detectado: " + id); }',
  '    else { hint.style.display = "none"; }',
  '  });',
  '  // v2.9: controles do chat',
  '  $("btn-add-controle").addEventListener("click", adicionarControle);',
  '  $("btn-aplicar-modelo").addEventListener("click", aplicarModelo);',
  '  $("f-modelo").addEventListener("change", function () {',
  '    // escolher um modelo não muda nada sozinho — o botão "Aplicar" age',
  '    if (["vbam","mgba","desmume","retroarch"].indexOf(this.value) !== -1) {',
  '      mostrarRes($("res-controles"), "aguardando", "Clique em ↺ Aplicar modelo para substituir a lista (ou continue editando à mão).");',
  '    }',
  '  });',
  '});',
  '</script>',
  '</body>',
  '</html>',
].join('\n');

module.exports = { PAGINA };
