/**
 * Página do assistente de configuração (v2.6) — HTML/CSS/JS embutido.
 * Segue o visual do overlay (dark gamer, verde/roxo) e NÃO usa recursos
 * externos: funciona offline e dentro do .exe empacotado.
 *
 * Segurança: nenhum dado do usuário ou do servidor vira HTML — tudo é
 * inserido via textContent / .value (sem innerHTML de dados).
 */

const PAGINA = [
  '<!DOCTYPE html>',
  '<html lang="pt-BR">',
  '<head>',
  '<meta charset="UTF-8">',
  '<meta name="viewport" content="width=device-width, initial-scale=1">',
  '<title>Pokemon Chat Plays — Assistente</title>',
  '<style>',
  '* { margin: 0; padding: 0; box-sizing: border-box; }',
  'body {',
  '  font-family: "Segoe UI", "Noto Sans", system-ui, sans-serif;',
  '  background: linear-gradient(135deg, #0b0d13 0%, #12161f 100%);',
  '  background-attachment: fixed;',
  '  color: #e8ecf3; padding: 28px 16px 120px;',
  '}',
  '.wrap { max-width: 900px; margin: 0 auto; }',
  'header { text-align: center; margin-bottom: 26px; }',
  'header h1 { font-size: 26px; letter-spacing: 0.5px; }',
  'header h1 .pkm { color: #facc15; }',
  'header .sub { color: #8b98ab; margin-top: 6px; font-size: 14px; }',
  'header .versao {',
  '  display: inline-block; margin-top: 10px; padding: 3px 12px;',
  '  background: rgba(250,204,21,0.15); color: #facc15; border-radius: 999px;',
  '  font-size: 12px; font-weight: 600;',
  '}',
  '.card {',
  '  background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08);',
  '  border-radius: 14px; padding: 22px; margin-bottom: 18px;',
  '}',
  '.card.inativo { opacity: 0.45; }',
  '.card-top { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 14px; }',
  '.card-top h2 { font-size: 18px; display: flex; align-items: center; gap: 8px; }',
  '.card-top .badge-plat { font-size: 11px; color: #8b98ab; font-weight: 400; }',
  '.campo { margin-bottom: 14px; }',
  '.campo label { display: block; font-size: 13px; color: #aab5c6; margin-bottom: 5px; font-weight: 600; }',
  '.campo input, .campo select {',
  '  width: 100%; padding: 10px 12px; font-size: 14px;',
  '  background: #0e131c; border: 1px solid rgba(255,255,255,0.12);',
  '  border-radius: 9px; color: #e8ecf3; outline: none;',
  '  transition: border-color 0.15s, box-shadow 0.15s;',
  '}',
  '.campo input:focus, .campo select:focus { border-color: #22c55e; box-shadow: 0 0 0 3px rgba(34,197,94,0.18); }',
  '.campo input[type=password] { font-family: Consolas, monospace; letter-spacing: 0.5px; }',
  '.campo .dica { font-size: 12px; color: #77839a; margin-top: 5px; line-height: 1.5; }',
  '.campo .dica a { color: #7dd3fc; }',
  '.linha { display: flex; gap: 14px; } .linha .campo { flex: 1; }',
  '.hint-id { font-size: 12px; margin-top: 5px; color: #86efac; display: none; }',
  '.caminho input { font-family: Consolas, monospace; font-size: 13px; }',
  '.linha-toggle { display: flex; align-items: center; justify-content: space-between; gap: 14px; padding: 12px 14px; margin-top: 4px; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.07); border-radius: 10px; }',
  '.linha-toggle .titulo { font-size: 14px; font-weight: 600; }',
  '.linha-toggle .sub { font-size: 12px; color: #77839a; margin-top: 3px; line-height: 1.5; }',
  '.switch { position: relative; width: 52px; height: 28px; flex: none; }',
  '.switch input { opacity: 0; width: 100%; height: 100%; position: absolute; cursor: pointer; z-index: 2; margin: 0; }',
  '.switch .trilho {',
  '  position: absolute; inset: 0; background: #2a3345; border-radius: 999px;',
  '  transition: background 0.18s;',
  '}',
  '.switch .bola {',
  '  position: absolute; top: 3px; left: 3px; width: 22px; height: 22px;',
  '  background: #8b98ab; border-radius: 50%; transition: left 0.18s, background 0.18s;',
  '}',
  '.switch input:checked ~ .trilho { background: rgba(34,197,94,0.35); }',
  '.switch input:checked ~ .bola { left: 27px; background: #22c55e; box-shadow: 0 0 10px rgba(34,197,94,0.6); }',
  '.acoes-plat { display: flex; align-items: center; gap: 12px; margin-top: 6px; }',
  '.btn {',
  '  padding: 10px 18px; font-size: 14px; font-weight: 600; cursor: pointer;',
  '  border-radius: 9px; border: 1px solid rgba(255,255,255,0.12);',
  '  background: #1e293b; color: #e8ecf3; transition: background 0.15s, transform 0.08s;',
  '}',
  '.btn:hover { background: #273549; } .btn:active { transform: scale(0.97); }',
  '.btn:disabled { opacity: 0.5; cursor: wait; }',
  '.btn.teste { background: rgba(167,139,250,0.15); border-color: rgba(167,139,250,0.35); color: #c4b5fd; }',
  '.btn.teste:hover { background: rgba(167,139,250,0.25); }',
  '.res { flex: 1; font-size: 13px; line-height: 1.5; display: none; padding: 8px 12px; border-radius: 8px; }',
  '.res.ok { display: block; background: rgba(34,197,94,0.12); color: #86efac; }',
  '.res.err { display: block; background: rgba(239,68,68,0.12); color: #fca5a5; }',
  '.res.aguardando { display: block; background: rgba(250,204,21,0.12); color: #fde68a; }',
  '.spinner {',
  '  display: inline-block; width: 14px; height: 14px; vertical-align: -2px;',
  '  border: 2px solid rgba(255,255,255,0.25); border-top-color: #fff;',
  '  border-radius: 50%; animation: girar 0.7s linear infinite; margin-right: 8px;',
  '}',
  '@keyframes girar { to { transform: rotate(360deg); } }',
  'details.avancado { border: 1px solid rgba(255,255,255,0.08); border-radius: 14px; background: rgba(255,255,255,0.02); }',
  'details.avancado summary {',
  '  padding: 16px 22px; cursor: pointer; font-size: 15px; font-weight: 600;',
  '  color: #aab5c6; list-style: none; user-select: none;',
  '}',
  'details.avancado summary::-webkit-details-marker { display: none; }',
  'details.avancado summary:before { content: "⚙  "; }',
  'details.avancado[open] summary { border-bottom: 1px solid rgba(255,255,255,0.08); }',
  'details.avancado .card { border: none; background: transparent; margin: 0; }',
  '.erros-gerais {',
  '  display: none; background: rgba(239,68,68,0.12); border: 1px solid rgba(239,68,68,0.35);',
  '  color: #fca5a5; border-radius: 10px; padding: 14px 18px; margin-bottom: 16px;',
  '  font-size: 13px; line-height: 1.6;',
  '}',
  '.barra-fix {',
  '  position: fixed; left: 0; right: 0; bottom: 0; z-index: 10;',
  '  background: rgba(11,13,19,0.92); backdrop-filter: blur(8px);',
  '  border-top: 1px solid rgba(255,255,255,0.08); padding: 14px 16px;',
  '}',
  '.barra-fix .dentro { max-width: 900px; margin: 0 auto; display: flex; align-items: center; gap: 14px; }',
  '.btn.primario {',
  '  background: linear-gradient(135deg, #16a34a, #22c55e); border-color: rgba(34,197,94,0.6);',
  '  color: #052e16; font-size: 15px; padding: 12px 26px;',
  '  box-shadow: 0 4px 18px rgba(34,197,94,0.35);',
  '}',
  '.btn.primario:hover { background: linear-gradient(135deg, #15803d, #16a34a); }',
  '.btn.fantasma { background: transparent; color: #8b98ab; }',
  '.btn.fantasma:hover { color: #e8ecf3; background: rgba(255,255,255,0.05); }',
  '.status { font-size: 12px; color: #8b98ab; margin-left: auto; }',
  '.status .pt { display: inline-block; width: 9px; height: 9px; border-radius: 50%; margin-right: 6px; background: #3a475a; }',
  '.status.on .pt { background: #22c55e; box-shadow: 0 0 8px #22c55e; }',
  '#tela-sucesso { display: none; text-align: center; padding: 60px 20px; }',
  '#tela-sucesso .emoji { font-size: 64px; margin-bottom: 16px; }',
  '#tela-sucesso h2 { font-size: 26px; margin-bottom: 10px; color: #86efac; }',
  '#tela-sucesso p { color: #aab5c6; font-size: 15px; line-height: 1.7; max-width: 520px; margin: 0 auto 8px; }',
  '#tela-sucesso .passos { text-align: left; background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; padding: 18px 24px; max-width: 560px; margin: 22px auto; font-size: 14px; line-height: 2; color: #c8d2e0; }',
  '.olho { position: absolute; right: 9px; top: 34px; background: none; border: none; cursor: pointer; font-size: 16px; opacity: 0.7; }',
  '.rel { position: relative; }',
  '@media (max-width: 640px) { .linha { flex-direction: column; gap: 0; } body { padding-bottom: 150px; } }',
  '</style>',
  '</head>',
  '<body>',
  '<div class="wrap">',
  '  <header>',
  '    <h1>🎮 <span class="pkm">Pokemon</span> Chat Plays</h1>',
  '    <div class="sub">Assistente de configuração — o chat da sua live no controle</div>',
  '    <div class="versao" id="versao">v?</div>',
  '  </header>',
  '',
  '  <div class="erros-gerais" id="erros-gerais"></div>',
  '',
  '  <div id="tela-form">',
  '',
  '  <div class="card" id="card-twitch">',
  '    <div class="card-top">',
  '      <h2>🟣 Twitch <span class="badge-plat">chat da sua live Twitch</span></h2>',
  '      <label class="switch"><input type="checkbox" id="tg-twitch" checked><span class="trilho"></span><span class="bola"></span></label>',
  '    </div>',
  '    <div class="linha">',
  '      <div class="campo">',
  '        <label for="f-usuario">Usuário do bot</label>',
  '        <input id="f-usuario" placeholder="ex.: meu_bot_zueiro" autocomplete="off">',
  '        <div class="dica">Crie uma <b>segunda conta</b> Twitch para o bot (não use a sua).</div>',
  '      </div>',
  '      <div class="campo">',
  '        <label for="f-canal">Canal que o bot monitora</label>',
  '        <input id="f-canal" placeholder="ex.: sindromegames" autocomplete="off">',
  '        <div class="dica">É o canal onde VOCÊ transmite (sem o #).</div>',
  '      </div>',
  '    </div>',
  '    <div class="campo rel">',
  '      <label for="f-token">Token OAuth do bot</label>',
  '      <input id="f-token" type="password" placeholder="oauth:..." autocomplete="off">',
  '      <button class="olho" id="olho-token" type="button" title="mostrar/ocultar">👁</button>',
  '      <div class="dica">Gere em <a href="https://twitchtokengenerator.com/" target="_blank" rel="noopener">twitchtokengenerator.com</a> → botão <b>Bot Chat Token</b> → copie o <b>Access token</b>. Cole com ou sem o "oauth:".</div>',
  '    </div>',
  '    <div class="acoes-plat">',
  '      <button class="btn teste" id="btn-twitch" type="button">🔌 Testar Twitch</button>',
  '      <div class="res" id="res-twitch"></div>',
  '    </div>',
  '  </div>',
  '',
  '  <div class="card" id="card-youtube">',
  '    <div class="card-top">',
  '      <h2>🔴 YouTube <span class="badge-plat">chat da sua live YouTube</span></h2>',
  '      <label class="switch"><input type="checkbox" id="tg-youtube"><span class="trilho"></span><span class="bola"></span></label>',
  '    </div>',
  '    <div class="campo rel">',
  '      <label for="f-ytkey">Chave de API do YouTube</label>',
  '      <input id="f-ytkey" type="password" placeholder="AIza..." autocomplete="off">',
  '      <button class="olho" id="olho-ytkey" type="button" title="mostrar/ocultar">👁</button>',
  '      <div class="dica">Crie grátis no <a href="https://console.cloud.google.com/" target="_blank" rel="noopener">Google Cloud Console</a>: crie um projeto → ative a <b>YouTube Data API v3</b> → Credenciais → Chave de API.</div>',
  '    </div>',
  '    <div class="campo">',
  '      <label for="f-ytvideo">ID ou URL da live</label>',
  '      <input id="f-ytvideo" placeholder="ex.: jfKfPfyJRdk ou https://youtube.com/watch?v=..." autocomplete="off">',
  '      <div class="hint-id" id="hint-video"></div>',
  '      <div class="dica">Cole o endereço da live direto do navegador — o bot extrai o ID sozinho. Cada live nova tem um ID novo.</div>',
  '    </div>',
  '    <div class="acoes-plat">',
  '      <button class="btn teste" id="btn-youtube" type="button">🔌 Testar YouTube</button>',
  '      <div class="res" id="res-youtube"></div>',
  '    </div>',
  '  </div>',
  '',
  '  <div class="card" id="card-jogo">',
  '    <div class="card-top">',
  '      <h2>🎮 Jogo / Emulador <span class="badge-plat">o programa que o chat vai controlar</span></h2>',
  '    </div>',
  '    <div class="campo caminho">',
  '      <label for="f-exe">Caminho do executável (o jogo que o bot abre e controla)</label>',
  '      <input id="f-exe" placeholder="C:\\Users\\Admin\\Downloads\\visualboyadvance-m-Win-x86_64\\visualboyadvance-m.exe" autocomplete="off" spellcheck="false">',
  '      <div class="dica">Cola o caminho completo do <b>.exe</b> (clique direito no arquivo → “Copiar como caminho”). Serve <b>qualquer programa</b>: VBA-M, mGBA, RetroArch, DeSmuME, Minecraft… Se já estiver aberto, o bot só vigia (não abre 2º).</div>',
  '    </div>',
  '    <div class="campo caminho">',
  '      <label for="f-rom">ROM do jogo (só se for emulador)</label>',
  '      <input id="f-rom" placeholder="C:\\Users\\Admin\\Downloads\\Pokemon - Esmeralda.gba" autocomplete="off" spellcheck="false">',
  '      <div class="dica">O bot abre o emulador <b>já com essa ROM</b> — e se o jogo fechar no meio da live, reabre com a <b>mesma ROM</b>. Deixa vazio para jogos sem ROM (Minecraft etc.).</div>',
  '    </div>',
  '    <div class="linha-toggle">',
  '      <div>',
  '        <div class="titulo">🔄 Reabrir o jogo se ele fechar</div>',
  '        <div class="sub">Fechou/c rash no meio da live? O bot reabre sozinho com a mesma ROM (até 5 quedas seguidas — depois avisa e para).</div>',
  '      </div>',
  '      <label class="switch"><input type="checkbox" id="tg-reabrir" checked><span class="trilho"></span><span class="bola"></span></label>',
  '    </div>',
  '    <div class="acoes-plat">',
  '      <button class="btn teste" id="btn-verificar-jogo" type="button">🔍 Verificar caminhos</button>',
  '      <button class="btn" id="btn-abrir-jogo" type="button">▶ Abrir agora</button>',
  '      <div class="res" id="res-jogo"></div>',
  '    </div>',
  '  </div>',
  '',
  '  <details class="avancado">',
  '    <summary>Avançado (opcional — já vem bom por padrão)</summary>',
  '    <div class="card">',
  '      <div class="linha">',
  '        <div class="campo">',
  '          <label for="f-cooldown">Cooldown por pessoa (ms)</label>',
  '          <input id="f-cooldown" type="number" min="0" step="100">',
  '          <div class="dica">Tempo mínimo entre comandos do MESMO espectador.</div>',
  '        </div>',
  '        <div class="campo">',
  '          <label for="f-duracao">Duração da tecla (ms)</label>',
  '          <input id="f-duracao" type="number" min="50" step="10">',
  '          <div class="dica">Quanto tempo cada tecla fica apertada no jogo.</div>',
  '        </div>',
  '      </div>',
  '      <div class="linha">',
  '        <div class="campo">',
  '          <label for="f-modo-inicial">Modo inicial</label>',
  '          <select id="f-modo-inicial">',
  '            <option value="anarquia">Anarquia (tudo executa na hora)</option>',
  '            <option value="democracia">Democracia (o mais votado executa)</option>',
  '          </select>',
  '        </div>',
  '        <div class="campo">',
  '          <label for="f-tecla-pausa">Tecla de pausa (streamer)</label>',
  '          <input id="f-tecla-pausa" placeholder="f9">',
  '          <div class="dica">Pausa/libera o chat na hora (evite teclas que o emulador usa).</div>',
  '        </div>',
  '      </div>',
  '      <div class="linha">',
  '        <div class="campo">',
  '          <label for="f-modo-teclado">Teclado</label>',
  '          <select id="f-modo-teclado">',
  '            <option value="janela">Janela (teclas só no emulador) — recomendado</option>',
  '            <option value="global">Global (teclas na janela em foco)</option>',
  '          </select>',
  '        </div>',
  '        <div class="campo">',
  '          <label for="f-preset">Preset do emulador</label>',
  '          <select id="f-preset">',
  '            <option value="vbam">VisualBoyAdvance-M</option>',
  '            <option value="mgba">mGBA</option>',
  '            <option value="desmume">DeSmuME</option>',
  '            <option value="retroarch">RetroArch</option>',
  '          </select>',
  '        </div>',
  '      </div>',
  '    </div>',
  '  </details>',
  '',
  '  </div><!-- /tela-form -->',
  '',
  '  <div id="tela-sucesso">',
  '    <div class="emoji">🎉</div>',
  '    <h2 id="sucesso-titulo">Configuração salva!</h2>',
  '    <p id="sucesso-txt"></p>',
  '    <div class="passos" id="sucesso-passos"></div>',
  '    <button class="btn primario" id="btn-fechar" type="button">Fechar assistente</button>',
  '  </div>',
  '',
  '</div>',
  '',
  '<div class="barra-fix">',
  '  <div class="dentro">',
  '    <button class="btn primario" id="btn-salvar" type="button">💾 Salvar e continuar</button>',
  '    <button class="btn fantasma" id="btn-sair" type="button">Sair sem salvar</button>',
  '    <div class="status" id="status"><span class="pt"></span><span id="status-txt">carregando...</span></div>',
  '  </div>',
  '</div>',
  '',
  '<script>',
  'var CAMPOS_SEGREDOS = ["f-token", "f-ytkey"];',
  'function $(id) { return document.getElementById(id); }',
  'function txt(el, mensagem) { el.textContent = mensagem; }',
  '',
  'function api(caminho, corpo) {',
  '  var op = corpo ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(corpo) } : {};',
  '  return fetch(caminho, op).then(function (r) { return r.json(); });',
  '}',
  '',
  'function mostrarRes(el, classe, mensagem) {',
  '  el.className = "res " + classe;',
  '  txt(el, mensagem);',
  '}',
  '',
  'function alternarCard(idToggle, idCard) {',
  '  var ativo = $(idToggle).checked;',
  '  $(idCard).className = ativo ? "card" : "card inativo";',
  '}',
  '',
  'function botaoCarregando(btn, carregando, rotulo) {',
  '  if (carregando) { btn.disabled = true; btn.innerHTML = \'<span class="spinner"></span>\' + rotulo; }',
  '  else { btn.disabled = false; btn.textContent = rotulo; }',
  '}',
  '',
  'function detectarId(valor) {',
  '  var bruto = String(valor || "").trim();',
  '  if (!bruto) return "";',
  '  if (bruto.indexOf("/") === -1 && bruto.indexOf("?") === -1) return "";',
  '  var m = bruto.match(/[?&]v=([A-Za-z0-9_-]{5,})/);',
  '  if (m) return m[1];',
  '  m = bruto.match(/youtu\\.be\\/([A-Za-z0-9_-]{5,})/);',
  '  if (m) return m[1];',
  '  m = bruto.match(/youtube\\.com\\/(?:live|shorts|embed)\\/([A-Za-z0-9_-]{5,})/);',
  '  if (m) return m[1];',
  '  return "";',
  '}',
  '',
  'function carregar() {',
  '  api("/api/estado").then(function (d) {',
  '    txt($("versao"), "v" + d.versao);',
  '    $("tg-twitch").checked = d.twitchAtivo;',
  '    $("tg-youtube").checked = d.youtubeAtivo;',
  '    alternarCard("tg-twitch", "card-twitch");',
  '    alternarCard("tg-youtube", "card-youtube");',
  '    var v = d.valores || {};',
  '    $("f-usuario").value = v.TWITCH_BOT_USERNAME || "";',
  '    $("f-canal").value = v.TWITCH_CHANNEL || "";',
  '    $("f-ytvideo").value = v.YOUTUBE_VIDEO_ID || "";',
  '    $("f-cooldown").value = v.COMMAND_COOLDOWN_MS || 1500;',
  '    $("f-duracao").value = v.KEY_PRESS_DURATION_MS || 230;',
  '    $("f-modo-inicial").value = v.MODO_INICIAL || "anarquia";',
  '    $("f-tecla-pausa").value = v.TECLA_PAUSA || "f9";',
  '    $("f-modo-teclado").value = v.MODO_TECLADO || "janela";',
  '    $("f-preset").value = v.EMULADOR_PRESET || "vbam";',
  '    $("f-exe").value = v.EMULADOR_EXE || "";',
  '    $("f-rom").value = v.JOGO_ROM || "";',
  '    $("tg-reabrir").checked = v.JOGO_AUTO_REINICIAR !== "false";',
  '    if (d.mascaras && d.mascaras.TWITCH_OAUTH_TOKEN) {',
  '      $("f-token").placeholder = "preenchido (" + d.mascaras.TWITCH_OAUTH_TOKEN + ") — deixe vazio para manter";',
  '    }',
  '    if (d.mascaras && d.mascaras.YOUTUBE_API_KEY) {',
  '      $("f-ytkey").placeholder = "preenchida (" + d.mascaras.YOUTUBE_API_KEY + ") — deixe vazio para manter";',
  '    }',
  '    var st = $("status");',
  '    st.className = "status " + (d.configurado ? "on" : "");',
  '    txt($("status-txt"), d.configurado ? "configuração atual válida" : "configuração incompleta");',
  '    if (d.modo === "primeiro-uso") {',
  '      txt($("btn-salvar"), "💾 Salvar e iniciar o bot");',
  '    }',
  '  }).catch(function () {',
  '    txt($("status-txt"), "sem contato com o bot");',
  '  });',
  '}',
  '',
  'function testarTwitch() {',
  '  var res = $("res-twitch");',
  '  res.className = "res";',
  '  botaoCarregando($("btn-twitch"), true, "Testando...");',
  '  api("/api/testar-twitch", {',
  '    TWITCH_BOT_USERNAME: $("f-usuario").value,',
  '    TWITCH_OAUTH_TOKEN: $("f-token").value,',
  '    TWITCH_CHANNEL: $("f-canal").value',
  '  }).then(function (r) {',
  '    botaoCarregando($("btn-twitch"), false, "🔌 Testar Twitch");',
  '    mostrarRes(res, r.ok ? "ok" : "err", (r.ok ? "✔ " : "✖ ") + r.mensagem);',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-twitch"), false, "🔌 Testar Twitch");',
  '    mostrarRes(res, "err", "✖ Falha ao testar: " + e);',
  '  });',
  '}',
  '',
  'function testarYoutube() {',
  '  var res = $("res-youtube");',
  '  res.className = "res";',
  '  botaoCarregando($("btn-youtube"), true, "Testando...");',
  '  api("/api/testar-youtube", {',
  '    YOUTUBE_API_KEY: $("f-ytkey").value,',
  '    YOUTUBE_VIDEO_ID: $("f-ytvideo").value',
  '  }).then(function (r) {',
  '    botaoCarregando($("btn-youtube"), false, "🔌 Testar YouTube");',
  '    var classe = r.ok ? "ok" : (r.aguardando ? "aguardando" : "err");',
  '    mostrarRes(res, classe, (r.ok ? "✔ " : (r.aguardando ? "⏳ " : "✖ ")) + r.mensagem);',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-youtube"), false, "🔌 Testar YouTube");',
  '    mostrarRes(res, "err", "✖ Falha ao testar: " + e);',
  '  });',
  '}',
  '',
  'function testarJogo() {',
  '  var res = $("res-jogo");',
  '  res.className = "res";',
  '  botaoCarregando($("btn-verificar-jogo"), true, "Verificando...");',
  '  api("/api/verificar-jogo", {',
  '    EMULADOR_EXE: $("f-exe").value.trim(),',
  '    JOGO_ROM: $("f-rom").value.trim()',
  '  }).then(function (r) {',
  '    botaoCarregando($("btn-verificar-jogo"), false, "🔍 Verificar caminhos");',
  '    var vazio = !$("f-exe").value.trim() && !$("f-rom").value.trim();',
  '    mostrarRes(res, r.ok ? "ok" : "err", (r.ok ? (vazio ? "ℹ " : "✔ ") : "✖ ") + r.mensagem);',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-verificar-jogo"), false, "🔍 Verificar caminhos");',
  '    mostrarRes(res, "err", "✖ Falha ao verificar: " + e);',
  '  });',
  '}',
  '',
  'function abrirJogo() {',
  '  var res = $("res-jogo");',
  '  res.className = "res";',
  '  botaoCarregando($("btn-abrir-jogo"), true, "Abrindo...");',
  '  api("/api/abrir-jogo", {',
  '    EMULADOR_EXE: $("f-exe").value.trim(),',
  '    JOGO_ROM: $("f-rom").value.trim()',
  '  }).then(function (r) {',
  '    botaoCarregando($("btn-abrir-jogo"), false, "▶ Abrir agora");',
  '    mostrarRes(res, r.ok ? "ok" : "err", (r.ok ? "✔ " : "✖ ") + r.mensagem);',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-abrir-jogo"), false, "▶ Abrir agora");',
  '    mostrarRes(res, "err", "✖ Falha ao abrir: " + e);',
  '  });',
  '}',
  '',
  'function salvar() {',
  '  var errosEl = $("erros-gerais");',
  '  errosEl.style.display = "none";',
  '  botaoCarregando($("btn-salvar"), true, "Salvando...");',
  '  api("/api/salvar", {',
  '    twitchAtivo: $("tg-twitch").checked,',
  '    youtubeAtivo: $("tg-youtube").checked,',
  '    jogoAutoReiniciar: $("tg-reabrir").checked,',
  '    TWITCH_BOT_USERNAME: $("f-usuario").value.trim(),',
  '    TWITCH_OAUTH_TOKEN: $("f-token").value.trim(),',
  '    TWITCH_CHANNEL: $("f-canal").value.trim(),',
  '    YOUTUBE_API_KEY: $("f-ytkey").value.trim(),',
  '    YOUTUBE_VIDEO_ID: $("f-ytvideo").value.trim(),',
  '    EMULADOR_EXE: $("f-exe").value.trim(),',
  '    JOGO_ROM: $("f-rom").value.trim(),',
  '    COMMAND_COOLDOWN_MS: $("f-cooldown").value,',
  '    KEY_PRESS_DURATION_MS: $("f-duracao").value,',
  '    MODO_INICIAL: $("f-modo-inicial").value,',
  '    TECLA_PAUSA: $("f-tecla-pausa").value.trim(),',
  '    MODO_TECLADO: $("f-modo-teclado").value,',
  '    EMULADOR_PRESET: $("f-preset").value',
  '  }).then(function (r) {',
  '    botaoCarregando($("btn-salvar"), false, "💾 Salvar e continuar");',
  '    if (r.ok) {',
  '      $("tela-form").style.display = "none";',
  '      document.querySelector(".barra-fix").style.display = "none";',
  '      document.querySelector("details.avancado").style.display = "none";',
  '      $("tela-sucesso").style.display = "block";',
  '      txt($("sucesso-titulo"), "Configuração salva! 🎉");',
  '      var linhas = [];',
  '      var temJogo = r.jogo && r.jogo.exe;',
  '      if (r.continuara) {',
  '        txt($("sucesso-txt"), "O bot já está continuando o boot — volte para a janela do terminal e aproveite a live!");',
  '        linhas.push("1. Volte para o terminal do bot (ele está subindo o Twitch/YouTube agora)");',
  '        if (temJogo) {',
  '          linhas.push("2. O bot abre o jogo " + r.jogo.nome + " sozinho" + (r.jogo.rom ? " com a ROM " + r.jogo.rom : "") + " — e reabre se fechar");',
  '          linhas.push("3. Diga pro chat digitar a, b, cima, baixo... e assista a mágica 🎮");',
  '        } else {',
  '          linhas.push("2. Abra o emulador com o jogo (VisualBoyAdvance-M, mGBA...)");',
  '          linhas.push("3. Deixe o bot perguntar qual é o .exe do emulador — Enter mantém o salvo");',
  '          linhas.push("4. Diga pro chat digitar a, b, cima, baixo... e assista a mágica 🎮");',
  '        }',
  '      } else {',
  '        txt($("sucesso-txt"), "Tudo pronto no .env — agora é só rodar o bot.");',
  '        linhas.push("1. Feche esta aba (ou clique no botão abaixo)");',
  '        linhas.push("2. Dê um duplo-clique no iniciar.bat (ou rode npm start)");',
  '        if (temJogo) {',
  '          linhas.push("3. O bot abre o jogo " + r.jogo.nome + " sozinho" + (r.jogo.rom ? " com a ROM " + r.jogo.rom : "") + " — e reabre se fechar");',
  '        } else {',
  '          linhas.push("3. Abra o emulador com o jogo e siga as instruções do terminal");',
  '        }',
  '        linhas.push("4. Diga pro chat digitar a, b, cima, baixo... e assista a mágica 🎮");',
  '      }',
  '      if (r.overlay) {',
  '        linhas.push("5. Overlay do OBS: " + r.overlay + " (Fontes → + → Navegador)");',
  '      }',
  '      var passos = $("sucesso-passos");',
  '      passos.textContent = "";',
  '      for (var i = 0; i < linhas.length; i++) {',
  '        var div = document.createElement("div");',
  '        txt(div, linhas[i]);',
  '        passos.appendChild(div);',
  '      }',
  '    } else {',
  '      errosEl.style.display = "block";',
  '      var lista = "Não foi possível salvar:";',
  '      for (var j = 0; j < (r.erros || []).length; j++) lista += "\\n• " + r.erros[j];',
  '      txt(errosEl, lista);',
  '      errosEl.style.whiteSpace = "pre-line";',
  '      window.scrollTo({ top: 0, behavior: "smooth" });',
  '    }',
  '  }).catch(function (e) {',
  '    botaoCarregando($("btn-salvar"), false, "💾 Salvar e continuar");',
  '    errosEl.style.display = "block";',
  '    txt(errosEl, "Falha ao salvar: " + e);',
  '  });',
  '}',
  '',
  'function sair() {',
  '  api("/api/encerrar", {}).then(function () {',
  '    $("tela-form").style.display = "none";',
  '    document.querySelector(".barra-fix").style.display = "none";',
  '    $("tela-sucesso").style.display = "block";',
  '    txt($("sucesso-titulo"), "Até mais! 👋");',
  '    txt($("sucesso-txt"), "Nada foi salvo — pode fechar esta aba.");',
  '    $("sucesso-passos").textContent = "";',
  '  }).catch(function () {});',
  '}',
  '',
  'document.addEventListener("DOMContentLoaded", function () {',
  '  carregar();',
  '  $("tg-twitch").addEventListener("change", function () { alternarCard("tg-twitch", "card-twitch"); });',
  '  $("tg-youtube").addEventListener("change", function () { alternarCard("tg-youtube", "card-youtube"); });',
  '  $("btn-twitch").addEventListener("click", testarTwitch);',
  '  $("btn-youtube").addEventListener("click", testarYoutube);',
  '  $("btn-verificar-jogo").addEventListener("click", testarJogo);',
  '  $("btn-abrir-jogo").addEventListener("click", abrirJogo);',
  '  $("btn-salvar").addEventListener("click", salvar);',
  '  $("btn-sair").addEventListener("click", sair);',
  '  $("btn-fechar").addEventListener("click", function () { window.close(); });',
  '  $("olho-token").addEventListener("click", function () {',
  '    var t = $("f-token"); t.type = t.type === "password" ? "text" : "password";',
  '  });',
  '  $("olho-ytkey").addEventListener("click", function () {',
  '    var t = $("f-ytkey"); t.type = t.type === "password" ? "text" : "password";',
  '  });',
  '  $("f-ytvideo").addEventListener("input", function () {',
  '    var id = detectarId(this.value);',
  '    var hint = $("hint-video");',
  '    if (id) { hint.style.display = "block"; txt(hint, "ID detectado: " + id); }',
  '    else { hint.style.display = "none"; }',
  '  });',
  '});',
  '</script>',
  '</body>',
  '</html>',
].join('\n');

module.exports = { PAGINA };
